### ISSUE TITLE
Blazor switches from tenant-specific dependency to default dependency 

### ISSUE THREAD

**Issue by y2k4life** [autofac/Autofac.AspNetCore.Multitenant#38] opened 2021-06-17 23:10 UTC
## Describe the Bug

This is based on the [Sandbox.AspNetCore5](https://github.com/autofac/Autofac.AspNetCore.Multitenant/tree/develop/samples/Sandbox.AspNetCore5) sample converted to Server Side Blazor.

A Blazor page is dependent on an object to be injected into the page `IDependency`. The dependency has a property, `Id`, which can be a, b, or base depending on which tenant is accessing the page. The `Id` is displayed on the page.

Accessing the page with `?tenant=a` you will see `a` on the page briefly then it quickly changes to `base`.

```
info: AutofaqMultitenantBlazor.Sandbox.Shared.QueryStringTenantIdentificationStrategy[0]
      Identified tenant: a
info: AutofaqMultitenantBlazor.Sandbox.Shared.Dependency[0]
      Disposing dependency 'a'.
warn: AutofaqMultitenantBlazor.Sandbox.Shared.QueryStringTenantIdentificationStrategy[0]
      Unable to identify tenant from query string. Falling back to default.
info: AutofaqMultitenantBlazor.Sandbox.Shared.Dependency[0]
      Disposing dependency 'base'.
```

## Steps to Reproduce

I have a repo based on the Sandbox.AspNetCore5 sample converted to a Blazor app.

[Autofac Multi-Tenant Blazor](https://github.com/y2k4life/AutofaqMultitenantBlazor)

## Expected Behavior

When accessing the page as tenant `a` the expected output is to see `a` on the page.

## Exception with Stack Trace

Not applicable

## Dependency Versions

Autofac.AspNetCore.Multitenant: 5.0.0
Autofac.Multitenant: 6.0.0
Autofac: 6.0.0

## Additional Info

Issue #25 has the same issue. The issue reported was fixed, but the tenant-specific dependencies are the same therefore this issue was not seen. I cloned the repo mentioned. I added an `Id` property to `WeatherForecastService`, similar to the sample. That repo is having same issue as I'm having with my sample.

**Comment by tillig** [comment] 2021-06-18 01:49
I'm not going to lie, I'm not a Blazor user and I don't personally have time to ramp up on it and troubleshoot it. There are a lot of interesting things there from linker optimizations to runtime differences that I'm not versed on.

Unless one of the other owners can jump in here, the best I can personally offer is:

- We have SourceLink enabled so you should be able to step into the code.
- We'd totally take a pull request if you can figure it out.

I'll obviously leave this open for now, but I can't personally attend to it in the foreseeable future. I'm sorry that's the case, but for various reasons... It is what it is. Sorry.

**Comment by alsami** [comment] 2021-06-18 04:42
Can you publish the blazor sample in some repository? Then I can take a look and see if it has anything to do with the library.

**Comment by y2k4life** [comment] 2021-06-18 05:13
[Autofaq Multitenant Blazor](https://github.com/y2k4life/AutofaqMultitenantBlazor)

While debugging one thing I did to eliminate complexity and to have a more predicable use case was to change  `QueryStringTenantIdentificationStrategy` to return the same tenant id. The same results happen the switch from `a` to `base`.

This change is not in the repo.

```
public bool TryIdentifyTenant(out object tenantId)
{
    tenantId = "a";
    return true;
}
```

From what I gather the `a` object is disposed, but I can't figure out why the `base` dependency is used if the `QueryStringTenantIdentificationStrategy` always sets tenantId to `a`.

**Comment by alsami** [comment] 2021-06-18 11:54
So I've spent some time debugging this and I think I found the problem but sadly no solution.

The call of the extension `AddServerSideBlazor()` registers the type `CircutFactory` which creates a `CircutHost`.
As you can see on the screenshot it uses `IServiceScopeFactory` (which is an `AutofacServiceScopeFactory`) to create a scope without previously running through the required middleware.

That scope is then passed along to the `CircutHost` and other components to resolve specific services.

![image](https://user-images.githubusercontent.com/2729205/122555306-6a98a000-d03a-11eb-8d7e-fc09ea8cdfa1.png)

After the `CircutHost` has been created the tenant-scope is lost when `CircutHost.InitializeAsync(..)` has been called. The scope that was previously created is only used and the `ITenantIdentificationStrategy` is never hit again. I see many other components like `Renderer` having a shared `IServiceProvider` or even creating their own.

At this point I really think that this is not a bug in the library but more like a "problem" of Blazor-Server.

@tillig @alistairjevans any thoughts on that?

**Comment by tillig** [comment] 2021-06-18 13:38
Let me restate this in non-Blazor terms:

- App starts and a container is created.
- Server process starts and creates a lifetime scope, starts using that as its base container.
- Requests come in and the server spawns a scope from that child scope instead of from the container directly.

Does that sound right?

If so, yeah, that seems like an issue in the Blazor server. Unclear if _Microsoft_ will consider it an issue, but it'd be worth filing something with them to find out.

Should they not consider it an issue, someone might need to figure out how to integrate with Blazor to allow things to work, similar to how we had to figure out some magic to make it work for this ASP.NET Core multitenant package. If there is some sort of additional package to make it work, I might encourage the community to create and support it rather than the core Autofac folks; I don't know that we have the bandwidth to take on ownership of another integration package at the moment.

**Comment by alsami** [comment] 2021-06-18 13:53
> Let me restate this in non-Blazor terms:
> 
> * App starts and a container is created.
> * Server process starts and creates a lifetime scope, starts using that as its base container.
> * Requests come in and the server spawns a scope from that child scope instead of from the container directly.

Exactly.



> If so, yeah, that seems like an issue in the Blazor server. Unclear if _Microsoft_ will consider it an issue, but it'd be worth filing something with them to find out.

I'll try to find the correct repository and fill an issue.

**Comment by y2k4life** [comment] 2021-06-18 17:55
Might I suggest a note in the documents. There is a lot of technology under the ASP.NET Core umbrella and the assumption is if something is built for ASP.NET Core then it covers all of this technology. No fault to ya'all you do a great job. I'm just making a suggestion that until this is figured out then it does not work with Blazor. I'm sure with Client Side Blazor this would not work either. I just want to help others that might spend the time going down this path only to find out it does not work.

I'm a Blazor user but not total versed on the inner workings of Blazor therefore I don't know if I would be much help. Don't even know if there is anything that can be done and this would need a solution from Microsoft.

**Comment by alsami** [comment] 2021-07-15 11:00
I was about to report an issue and spent a few minutes thinking about it again. I came to the conclusion that this is not a bug (not with this library, nor with Blazor WASM) and we do simply not support this scenario. 

Why so? Blazor does a protocol switch at some point once the content has been delivered and the web-assembly bits have been loaded. From that point on, there is simply no middle-ware being executed because the code lives in the browser rather than communicating with the server.

I found this [library](https://github.com/Blazored/Localisation/tree/preview6) that has an interesting workaround to make localization middle-ware work, even after WASM has kicked in.

So we have three options now:
- We simple state that we do not support Blazor WASM for multi-tenancy. (not the best choice IMO)
- We create a feature request issue and hope for somebody to pick it up by integrating it in the current library or creating a new one
- We create a feature request issue and do it on our own by integrating it in the current library or creating a new one

**Comment by tillig** [comment] 2021-07-15 14:30
I'm fine with creating the feature request issue, but I don't personally have time to allocate to solving it. If someone else has that time, _awesome_.

**Comment by y2k4life** [comment] 2021-07-20 22:48
One clarification I tried this on server side Blazor not client. Don't know if this applies to both service and WASM. Or if there is one solution for one but not the other or if a solution would apply to both.

**Comment by tillig** [comment] 2021-11-14 17:42
It's been a few months and I don't think there's going to be any traction here. Since I'm not a Blazor user I can't even propose what we might put in the docs, so if someone wants it documented there's going to need to be a PR to the [documentation repo](https://github.com/autofac/Documentation).

I don't know that we have the community and ownership bandwidth to support a new integration, so unless someone out in the community wants to fire that up and own it, I unfortunately don't think we'll be doing anything as far as creating new integration packages.

If there's something that can be easily done to this package to make it work, I'm all for it; but I gather from previous comments that it is likely not a five-line change. (I mean, maybe it is?)

Point being, it doesn't look like there's anyone jumping on this to solve it at the moment. If a PR comes in for it, we'll be happy to check it out; if it's a new library, hopefully the community can bridge the gap. In either case, since it doesn't seem like we'll be moving forward on this in the foreseeable future, I'm going to close the issue. If said PR comes in, we'd be happy to reopen it.

**Closed as completed by tillig** 2021-11-14 17:42 UTC
